import { createPullRequest } from "../../../lib/github/pr.js";
import { getTask, updateTask } from "../../../lib/tasks/store.js";

export async function POST(
  _req: Request,
  context: { params: { taskId: string } },
) {
  const taskId = context.params.taskId;
  const task = await getTask(taskId);

  if (!task) {
    return Response.json({ error: "Task not found" }, { status: 404 });
  }

  if (!task.branchName) {
    return Response.json({ error: "Task does not have a branch yet" }, { status: 400 });
  }

  if (task.status !== "completed") {
    return Response.json(
      { error: "Task must be completed before opening a pull request" },
      { status: 400 },
    );
  }

  try {
    const pr = await createPullRequest({
      repoUrl: task.repoUrl,
      branchName: task.branchName,
      title: task.title,
      body: [
        "## Product Forge Agent Task",
        "",
        task.prompt,
        "",
        "This pull request was generated by a coding agent running in Vercel Sandbox.",
      ].join("\n"),
    });

    await updateTask(taskId, { prUrl: pr.url });

    return Response.json({ pr });
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    return Response.json({ error: message }, { status: 500 });
  }
}
