import { runInBackground } from "../../lib/utils/background.js";
import { createTask, getTask, listTasks, updateTask } from "../../lib/tasks/store.js";
import { continueTask, processTask } from "../../lib/tasks/processor.js";
import { createPullRequest } from "../../lib/github/pr.js";
const AGENTS = ["claude", "cursor", "codex", "gemini", "opencode"];
function isAgentType(value) {
    return AGENTS.includes(value);
}
export async function listTasksHandler(_req, res) {
    const tasks = await listTasks();
    res.json({ tasks });
}
export async function createTaskHandler(req, res) {
    const body = req.body;
    if (!body.prompt?.trim()) {
        res.status(400).json({ error: "prompt is required" });
        return;
    }
    if (!body.selectedAgent || !isAgentType(body.selectedAgent)) {
        res.status(400).json({
            error: `selectedAgent must be one of: ${AGENTS.join(", ")}`,
        });
        return;
    }
    const task = await createTask({
        prompt: body.prompt.trim(),
        repoUrl: body.repoUrl?.trim() ?? "",
        selectedAgent: body.selectedAgent,
        selectedModel: body.selectedModel,
        keepAlive: body.keepAlive ?? true,
        installDependencies: body.installDependencies ?? true,
        enableBrowser: body.enableBrowser ?? false,
        maxDuration: body.maxDuration,
    });
    runInBackground(processTask(task.id).catch((error) => {
        console.error(`Task ${task.id} failed:`, error);
    }));
    res.status(201).json({ task });
}
export async function getTaskHandler(req, res) {
    const task = await getTask(req.params.taskId);
    if (!task) {
        res.status(404).json({ error: "Task not found" });
        return;
    }
    res.json({ task });
}
export async function continueTaskHandler(req, res) {
    const taskId = req.params.taskId;
    const task = await getTask(taskId);
    if (!task) {
        res.status(404).json({ error: "Task not found" });
        return;
    }
    const message = req.body.message?.trim();
    if (!message) {
        res.status(400).json({ error: "message is required" });
        return;
    }
    runInBackground(continueTask(taskId, message).catch((error) => {
        console.error(`Follow-up for task ${taskId} failed:`, error);
    }));
    res.json({ success: true });
}
export async function createPullRequestHandler(req, res) {
    const taskId = req.params.taskId;
    const task = await getTask(taskId);
    if (!task) {
        res.status(404).json({ error: "Task not found" });
        return;
    }
    if (!task.branchName) {
        res.status(400).json({ error: "Task does not have a branch yet" });
        return;
    }
    if (task.status !== "completed") {
        res.status(400).json({
            error: "Task must be completed before opening a pull request",
        });
        return;
    }
    try {
        const pr = await createPullRequest({
            repoUrl: task.repoUrl,
            branchName: task.branchName,
            title: task.title,
            body: [
                "## Product Forge Agent Task",
                "",
                task.prompt,
                "",
                "This pull request was generated by a coding agent running in a remote sandbox.",
            ].join("\n"),
        });
        await updateTask(taskId, { prUrl: pr.url });
        res.json({ pr });
    }
    catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        res.status(500).json({ error: message });
    }
}
